---
- name: Start perf recording with hostname in output file
  hosts: all
  become: yes
  tasks:
    - name: Determine shortened hostname
      set_fact:
        short_hostname: "{{ ansible_hostname.split('.')[0] }}"

    - name: Create directory for perf output
      file:
        path: /pbsusers/perf
        state: directory
        mode: '0755'

    - name: Start perf recording
      shell: |
        nohup perf record -F 99 -a -g -o /pbsusers/perf/perf_{{ short_hostname }}.data </dev/null >/dev/null 2>&1 &
        echo $! > /pbsusers/perf/perf_{{ short_hostname }}.pid