#!/bin/bash
#
# Usage: ansible_gen_inventory.sh <number of worker nodes>
#
# Ansible test: 
# ANSIBLE_HOST_KEY_CHECKING=False ansible -i temp workernodes -m ping

# Specify the number of nodes as a argument to the script
numnodes=$1

# Check if atleast 1 worker node
if ((numnodes < 1)); then
echo "Number of worker nodes should be atleast 1"
exit 1
fi

# Generate the ansible inventory
echo "# This file is autogenerated"
echo "# Worker nodes"
echo "[workernodes]"
for ((i=0; i<numnodes; i++)); do
workerhostname=$(hostname | sed "s/head/node$i/")
workerpcname=$(nslookup $workerhostname | grep Name | awk '{print $2}')
workername=$workerhostname
echo $workername
done

echo "# Login nodes"
echo "[loginnodes]"
loginhostname=$(hostname | sed "s/head/login/")
loginpcname=$(nslookup $loginhostname | grep Name | awk '{print $2}')
loginname=$loginhostname
echo $loginname

echo "# All nodes"
echo "[multi:children]"
echo "workernodes"
echo "loginnodes"

echo "# Variables for all nodes"
echo "[multi:vars]"
echo "ansible_user=root"
echo "ansible_private_key_file=/root/.ssh/id_rsa"
echo "ansible_host_key_checking=False"
serverhostname=$(hostname)
serverpcname=$(nslookup $serverhostname | grep Name | awk '{print $2}')
echo "server_canonical_name=$serverpcname"
echo "server_name=$serverhostname"