---
- name: Configure worker nodes.
  become: true
  hosts: workernodes
  tasks:

    - name: Configure MoM usecp
      shell: |
        echo " False
        \$restrict_user_maxsysid 999
        \$usecp *:/pbsusers/ /pbsusers/" > /var/spool/pbs/mom_priv/config
  
    - name: HUP MoM
      shell: |
        kill -HUP `ps aux | grep /opt/pbs/sbin/pbs_mom | awk '{print $2}' | head -n 1`