
---
- name: Configure & Install MPICH on head node.
  become: true
  hosts: headnode
  tasks:
    
    - name: Strict host checking disable
      shell: |
        echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
        

- name: Configure & Install MPICH on all nodes.
  become: true
  hosts: multi
  tasks:
    
    - name: Strict host checking disable
      shell: |
        echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config