---
- name: Configure NFS server.
  become: true
  hosts: headnode
  tasks:

    - name: Install NFS server.
      command: apt install -y nfs-kernel-server

    - name: Create NFS directory.
      command: mkdir -p /pbsusers

    - name: Backup original /etc/exports.
      command: mv /etc/exports /etc/exports.orig

    # - name: Write to /etc/exports.
    #   shell: |
    #     echo "/pbsusers 10.10.1.0/255.255.255.0(rw,no_subtree_check)" > /etc/exports
    
    - name: Write worker nodes to /etc/exports.
      command: >
        bash -c '
        for ((i=0; i<{{ numworkernodes }}; i++)); do
          workerhostname=$(hostname | sed "s/head/node$i/")
          echo "/pbsusers $workerhostname(rw,no_subtree_check)" >> /etc/exports
        done'
    
    - name: Write login node to /etc/exports.
      command: >
        bash -c '
          loginhostname=$(hostname | sed "s/head/login/")
          echo "/pbsusers $loginhostname(rw,no_subtree_check)" >> /etc/exports'


    - name: Start NFS server.
      command: systemctl start nfs-kernel-server
    
    - name: Create test file.
      shell: |
        echo "Hello from $(hostname)" >> /pbsusers/test.txt


- name: Configure NFS clients.
  become: true
  hosts: multi
  tasks:

    - name: Install NFS client.
      command: apt install -y nfs-common

    # Instead use AutoFS
    # - name: Create NFS mount point.
    #   command: mkdir -p /pbsusers

    # - name: Mount the NFS directory.
    #   command: mount {{ serverhostname }}:/pbsusers /pbsusers

    - name: Install AutoFS.
      command: apt install -y autofs

    - name: Configure AutoFS - /etc/auto.master.
      shell: |
        echo "/ /etc/auto.nfs --ghost --timeout=60" >> /etc/auto.master

    - name: Configure AutoFS - /etc/auto.nfs.
      shell: |
        echo "/pbsusers -fstype=nfs4,rw {{ serverhostname }}:/pbsusers" >> /etc/auto.nfs

    - name: Restart AutoFS.
      shell: systemctl restart autofs
