---

- name: Configure worker nodes.
  gather_facts: true
  hosts: workernodes
  tasks:

    # TODO: Update PBS_SERVER to canonical name
    - name: Configure OpenPBS at /etc/pbs.conf
      become: true
      shell: |
        echo "PBS_EXEC=/opt/pbs
        PBS_SERVER={{ server_name }}
        PBS_START_SERVER=0
        PBS_START_SCHED=0
        PBS_START_COMM=0
        PBS_START_MOM=1
        PBS_MOM_NODE_NAME=$(hostname | awk -f '.' '{print $1}')
        PBS_HOME=/var/spool/pbs
        PBS_CORE_LIMIT=unlimited
        PBS_SCP=/usr/bin/scp" > /etc/pbs.conf
  
    - name: Start OpenPBS service.
      become: true
      command: systemctl start pbs

    - name: Configure OpenPBS to start automatically during system boot.
      become: true
      command: systemctl enable pbs