#------------------------------------------------------------------------------
#	Yash Kurkure
#	NetID - ykurku2
#	CS494 - Intro to HPC
#	Assignment 01
#	03/06/2023
#
#	I certify that this is my own work and where appropriate an extension
#	of the starter code provided for the assignment.
#------------------------------------------------------------------------------

CXX=g++
CXXFLAGS = -Wall -Wextra -fopenmp

scaling_study: scaling_study.cc
	$(CXX) $(CXXFLAGS) $< -o $@