---
- name: Configure redis client on worker nodes
  become: true
  hosts: workernodes
  tasks:

    - name: Update & install linux tools
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - linux-tools-common
        - linux-tools-generic