---
- name: Configure flame graph
  become: true
  hosts: all
  tasks:


    - name: Install linux tools
      shell: |
        sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`