---
- name: Install Kafka
  become: true
  hosts: headnode
  tasks:

  - name: Update & Install dependencies
    ansible.builtin.apt:
      update_cache: yes
      pkg:
      - default-jdk
    
  - name: Download Kafka tarball
    get_url:
      url: https://downloads.apache.org/kafka/3.8.0/kafka_2.12-3.8.0.tgz
      dest: /tmp/kafka.tgz
  
  - name: Extract Kafka archive
    unarchive:
      src: /tmp/kafka.tgz
      dest: /opt
      remote_src: yes

  - name: Rename Kafka directory
    file:
      src: /opt/kafka_2.12-3.8.0
      dest: /opt/kafka
      state: link

- name: Manage Kafka and Zookeeper Service
  hosts: headnode
  become: yes

  tasks:

    - name: Ensure Zookeeper log file exists
      file:
        path: /local/zookeeper_service.log
        state: touch
    
    - name: Ensure Kafka log file exists
      file:
        path: /local/kafka_service.log
        state: touch

    - name: Copy Zookeeper service file
      copy:
        src: /local/repository/services/zookeeper.service
        dest: /etc/systemd/system/zookeeper.service
        mode: '0644'  # Set permissions: owner read/write, others read-only
        backup: yes   # Create a backup before overwriting
        remote_src: yes  # Copy from the Ansible control node to the remote target

    - name: Copy Kafka service file
      copy:
        src: /local/repository/services/kafka.service
        dest: /etc/systemd/system/kafka.service
        mode: '0644'  # Set permissions: owner read/write, others read-only
        backup: yes   # Create a backup before overwriting
        remote_src: yes  # Copy from the Ansible control node to the remote target

    - name: Enable Zookeeper service
      systemd:
        name: zookeeper.service
        enabled: yes
        daemon_reload: yes  # Reload systemd configuration after enabling

    - name: Start Zookeeper service 
      systemd:
        name: zookeeper.service
        state: started
        daemon_reload: yes

    - name: Enable Kafka service
      systemd:
        name: kafka.service
        enabled: yes
        daemon_reload: yes  # Reload systemd configuration after enabling

    - name: Start Kafka service 
      systemd:
        name: kafka.service
        state: started
        daemon_reload: yes