---
- name: Install Kafka
  become: true
  hosts: all
  tasks:

  - name: Update & Install dependencies
    ansible.builtin.apt:
      update_cache: yes
      pkg:
      - default-jdk
  
  - name: Install Confluent Kafka Python Client
    shell: |
      sudo apt -y install python3-pip
      pip install kafka-python
    
  - name: Download Kafka tarball
    get_url:
      url: https://downloads.apache.org/kafka/3.8.0/kafka_2.12-3.8.0.tgz
      dest: /tmp/kafka.tgz
  
  - name: Extract Kafka archive
    unarchive:
      src: /tmp/kafka.tgz
      dest: /opt
      remote_src: yes

  - name: Rename Kafka directory
    file:
      src: /opt/kafka_2.12-3.8.0
      dest: /opt/kafka
      state: link

- name: Manage Kafka and Zookeeper Service
  hosts: headnode
  become: yes

  tasks:

    - name: Update Kafka server config
      shell: |
        echo "broker.id=0
        listeners=PLAINTEXT://{{ serverhostname }}:9092
        num.network.threads=3
        num.io.threads=8
        socket.send.buffer.bytes=102400
        socket.receive.buffer.bytes=102400
        socket.request.max.bytes=104857600
        log.dirs=/tmp/kafka-logs
        num.partitions=1
        num.recovery.threads.per.data.dir=1
        offsets.topic.replication.factor=1
        transaction.state.log.replication.factor=1
        transaction.state.log.min.isr=1
        log.retention.hours=168
        log.retention.check.interval.ms=300000
        zookeeper.connect=localhost:2181
        zookeeper.connection.timeout.ms=18000
        group.initial.rebalance.delay.ms=0" > /opt/kafka/config/server.properties


    - name: Ensure Zookeeper log file exists
      file:
        path: /local/zookeeper_service.log
        state: touch
    
    - name: Ensure Kafka log file exists
      file:
        path: /local/kafka_service.log
        state: touch

    - name: Copy Zookeeper service file
      copy:
        src: /local/repository/kafka/zookeeper.service
        dest: /etc/systemd/system/zookeeper.service
        mode: '0644'
        backup: yes
        remote_src: yes

    - name: Copy Kafka service file
      copy:
        src: /local/repository/kafka/kafka.service
        dest: /etc/systemd/system/kafka.service
        mode: '0644'
        backup: yes
        remote_src: yes

    - name: Enable Zookeeper service
      systemd:
        name: zookeeper.service
        enabled: yes
        daemon_reload: yes

    - name: Start Zookeeper service 
      systemd:
        name: zookeeper.service
        state: started
        daemon_reload: yes

    - name: Enable Kafka service
      systemd:
        name: kafka.service
        enabled: yes
        daemon_reload: yes

    - name: Start Kafka service 
      systemd:
        name: kafka.service
        state: started
        daemon_reload: yes