---
# Example of passing variables
#  --extra-vars "cap=25"
# A cap can be applied from 25% to 100%
- name: Apply a powercap to all nodes that support
  become: true
  hosts: workernodes
  tasks:

    - name: Get the number of RAPL zones
      register: nzones_result
      shell: powercap-info intel-rapl --nzones

    - name: Calculate and set power constraints
      loop: "{{ range(0, nzones_result.stdout | int) }}"
      vars:
        zone_index: "{{ loop.index }}"
        max_power_filename: "/sys/class/powercap/intel-rapl/intel-rapl:{{ zone_index }}/constraint_1_max_power_uw"
        power_constraint: "{{ (max_power | int) * cap }}"

      tasks:
        - name: Read the current max power
          register: max_power
          shell: "cat {{ max_power_filename }}"  

        - name: Set the new power constraint
          shell: "powercap-set intel-rapl -z {{ zone_index }} -c 1 -l {{ power_constraint }}"
          failed_when: power_constraint.rc != 0  
          become: true
    

