---
# Example of passing variables
#  --extra-vars "cap=0.25"
# A cap can be applied from 0.25 to 1
- name: Apply a powercap to all nodes that support
  become: true
  hosts: workernodes
  tasks:

    - name: Update /local/repository
      shell: cd /local/repository && git pull origin master

    - name: Excute powercap script
      shell: /local/repository/cloudlab/setpowercap.sh {{ cap }}
    

