---
- name: Install Python 3.9 and configure update-alternatives
  hosts: all
  become: yes

  vars:
    python39_package:  
      - "python39"  # Fedora 
      - "python3.9" # RHEL/CentOS

  tasks:
    - name: Ensure required dependencies are present (RHEL/CentOS)
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - openssl-devel
        - bzip2-devel
        - libffi-devel
        - zlib-devel
      when: ansible_distribution in ["RedHat", "CentOS"]

    - name: Install Python 3.9
      package:
        name: "{{ python39_package }}"
        state: present

    - name: Add Python 3.9 to update-alternatives
      alternatives:
        name: python3 # Set the general 'python3' alternative
        path: /usr/bin/python3.9
        link: /usr/bin/python3
        priority: 10 # Give it a higher priority

    - name: Check if Python 3.9 is set as default 
      command: python3 --version
      register: python_version_check

    - name: Print Python version (for debug)
      debug:
        var: python_version_check.stdout